eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8070
spring:
  application:
    name: binarfood-service
    # Send email
  mail:
    host: smtp.gmail.com
    port: 587
    username: depanbelakang944@gmail.com
    password: bglxmoxhroikcpua
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 2a81eba9b378a3795f05
            client-secret: 0418b60668b66239e8039b559e0fecbe0cdba998
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/chapter8
    username: postgres
    password: Bangsat@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    driverClassName: org.postgresql.Driver

# Own secret
binarfud:
  app:
    jwtSecret: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629
    jwtExpirationMs: 3600000


